wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715965632
    t:
      1:
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 2
      - 23
      - 61
      4: 3.10.13
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
    framework: torch
